// Offline Iconify registry — icon bodies live in src/assets/iconify-local.json
// (generated by scripts/generate-icon-set.mjs from the installed @iconify-json sets).
// We import `@iconify/vue/offline`, a build with the HTTP API stripped out, so the
// app can never reach api.iconify.design even for a typo.
import { addCollection } from '@iconify/vue/offline'
import local from '@/assets/iconify-local.json'

export type IconName = `${string}:${string}`

const registry = local as unknown as Record<
  string,
  { prefix: string; icons: Record<string, unknown>; width?: number; height?: number }
>

let registered = false

/** Register every locally-bundled icon collection. Idempotent. */
export function registerLocalIcons(): void {
  if (registered) return
  registered = true
  for (const collection of Object.values(registry)) {
    addCollection(collection as never)
  }
}

/** True when the icon body is present in the local bundle. */
export function hasLocalIcon(name: string): boolean {
  const sep = name.indexOf(':')
  if (sep < 1) return false
  const collection = registry[name.slice(0, sep)]
  return !!collection && !!collection.icons[name.slice(sep + 1)]
}

registerLocalIcons()
